// Code generated by pigeon; DO NOT EDIT.

package parse

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "EmailEntry",
			pos:  position{line: 5, col: 1, offset: 19},
			expr: &ruleRefExpr{
				pos:  position{line: 5, col: 15, offset: 33},
				name: "Email",
			},
		},
		{
			name: "SalaryEntry",
			pos:  position{line: 6, col: 1, offset: 39},
			expr: &ruleRefExpr{
				pos:  position{line: 6, col: 16, offset: 54},
				name: "Salary",
			},
		},
		{
			name: "LocationEntry",
			pos:  position{line: 7, col: 1, offset: 61},
			expr: &ruleRefExpr{
				pos:  position{line: 7, col: 18, offset: 78},
				name: "Location",
			},
		},
		{
			name: "URLEntry",
			pos:  position{line: 8, col: 1, offset: 87},
			expr: &ruleRefExpr{
				pos:  position{line: 8, col: 13, offset: 99},
				name: "URL",
			},
		},
		{
			name: "TrapEntry",
			pos:  position{line: 9, col: 1, offset: 103},
			expr: &ruleRefExpr{
				pos:  position{line: 9, col: 14, offset: 116},
				name: "Trap",
			},
		},
		{
			name: "Email",
			pos:  position{line: 11, col: 1, offset: 122},
			expr: &actionExpr{
				pos: position{line: 11, col: 10, offset: 131},
				run: (*parser).callonEmail1,
				expr: &seqExpr{
					pos: position{line: 11, col: 10, offset: 131},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 11, col: 10, offset: 131},
							name: "User",
						},
						&litMatcher{
							pos:        position{line: 11, col: 15, offset: 136},
							val:        "@",
							ignoreCase: false,
							want:       "\"@\"",
						},
						&ruleRefExpr{
							pos:  position{line: 11, col: 19, offset: 140},
							name: "Domain",
						},
					},
				},
			},
		},
		{
			name: "User",
			pos:  position{line: 15, col: 1, offset: 183},
			expr: &oneOrMoreExpr{
				pos: position{line: 15, col: 9, offset: 191},
				expr: &charClassMatcher{
					pos:        position{line: 15, col: 9, offset: 191},
					val:        "[a-zA-Z0-9._%+-]",
					chars:      []rune{'.', '_', '%', '+', '-'},
					ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "Domain",
			pos:  position{line: 16, col: 1, offset: 209},
			expr: &seqExpr{
				pos: position{line: 16, col: 11, offset: 219},
				exprs: []any{
					&oneOrMoreExpr{
						pos: position{line: 16, col: 11, offset: 219},
						expr: &charClassMatcher{
							pos:        position{line: 16, col: 11, offset: 219},
							val:        "[a-zA-Z0-9.-]",
							chars:      []rune{'.', '-'},
							ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&litMatcher{
						pos:        position{line: 16, col: 26, offset: 234},
						val:        ".",
						ignoreCase: false,
						want:       "\".\"",
					},
					&ruleRefExpr{
						pos:  position{line: 16, col: 30, offset: 238},
						name: "TLD",
					},
				},
			},
		},
		{
			name: "TLD",
			pos:  position{line: 17, col: 1, offset: 242},
			expr: &seqExpr{
				pos: position{line: 17, col: 8, offset: 249},
				exprs: []any{
					&charClassMatcher{
						pos:        position{line: 17, col: 8, offset: 249},
						val:        "[a-zA-Z]",
						ranges:     []rune{'a', 'z', 'A', 'Z'},
						ignoreCase: false,
						inverted:   false,
					},
					&charClassMatcher{
						pos:        position{line: 17, col: 17, offset: 258},
						val:        "[a-zA-Z]",
						ranges:     []rune{'a', 'z', 'A', 'Z'},
						ignoreCase: false,
						inverted:   false,
					},
					&zeroOrOneExpr{
						pos: position{line: 17, col: 26, offset: 267},
						expr: &charClassMatcher{
							pos:        position{line: 17, col: 26, offset: 267},
							val:        "[a-zA-Z]",
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&zeroOrOneExpr{
						pos: position{line: 17, col: 36, offset: 277},
						expr: &charClassMatcher{
							pos:        position{line: 17, col: 36, offset: 277},
							val:        "[a-zA-Z]",
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&zeroOrOneExpr{
						pos: position{line: 17, col: 46, offset: 287},
						expr: &charClassMatcher{
							pos:        position{line: 17, col: 46, offset: 287},
							val:        "[a-zA-Z]",
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&zeroOrOneExpr{
						pos: position{line: 17, col: 56, offset: 297},
						expr: &charClassMatcher{
							pos:        position{line: 17, col: 56, offset: 297},
							val:        "[a-zA-Z]",
							ranges:     []rune{'a', 'z', 'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "Salary",
			pos:  position{line: 19, col: 1, offset: 308},
			expr: &actionExpr{
				pos: position{line: 19, col: 11, offset: 318},
				run: (*parser).callonSalary1,
				expr: &seqExpr{
					pos: position{line: 19, col: 12, offset: 319},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 19, col: 12, offset: 319},
							name: "SalaryPart",
						},
						&zeroOrOneExpr{
							pos: position{line: 19, col: 23, offset: 330},
							expr: &seqExpr{
								pos: position{line: 19, col: 24, offset: 331},
								exprs: []any{
									&zeroOrOneExpr{
										pos: position{line: 19, col: 24, offset: 331},
										expr: &ruleRefExpr{
											pos:  position{line: 19, col: 24, offset: 331},
											name: "Spacing",
										},
									},
									&choiceExpr{
										pos: position{line: 19, col: 34, offset: 341},
										alternatives: []any{
											&litMatcher{
												pos:        position{line: 19, col: 34, offset: 341},
												val:        "-",
												ignoreCase: false,
												want:       "\"-\"",
											},
											&litMatcher{
												pos:        position{line: 19, col: 40, offset: 347},
												val:        "to",
												ignoreCase: true,
												want:       "\"to\"i",
											},
										},
									},
									&zeroOrOneExpr{
										pos: position{line: 19, col: 47, offset: 354},
										expr: &ruleRefExpr{
											pos:  position{line: 19, col: 47, offset: 354},
											name: "Spacing",
										},
									},
									&ruleRefExpr{
										pos:  position{line: 19, col: 56, offset: 363},
										name: "SalaryPart",
									},
								},
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 19, col: 69, offset: 376},
							expr: &seqExpr{
								pos: position{line: 19, col: 70, offset: 377},
								exprs: []any{
									&zeroOrOneExpr{
										pos: position{line: 19, col: 70, offset: 377},
										expr: &ruleRefExpr{
											pos:  position{line: 19, col: 70, offset: 377},
											name: "Spacing",
										},
									},
									&ruleRefExpr{
										pos:  position{line: 19, col: 79, offset: 386},
										name: "Frequency",
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SalaryPart",
			pos:  position{line: 23, col: 1, offset: 435},
			expr: &seqExpr{
				pos: position{line: 23, col: 15, offset: 449},
				exprs: []any{
					&zeroOrOneExpr{
						pos: position{line: 23, col: 15, offset: 449},
						expr: &seqExpr{
							pos: position{line: 23, col: 16, offset: 450},
							exprs: []any{
								&ruleRefExpr{
									pos:  position{line: 23, col: 16, offset: 450},
									name: "Currency",
								},
								&zeroOrOneExpr{
									pos: position{line: 23, col: 25, offset: 459},
									expr: &ruleRefExpr{
										pos:  position{line: 23, col: 25, offset: 459},
										name: "Spacing",
									},
								},
							},
						},
					},
					&ruleRefExpr{
						pos:  position{line: 23, col: 36, offset: 470},
						name: "Amount",
					},
					&zeroOrOneExpr{
						pos: position{line: 23, col: 43, offset: 477},
						expr: &charClassMatcher{
							pos:        position{line: 23, col: 43, offset: 477},
							val:        "[kK]",
							chars:      []rune{'k', 'K'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&zeroOrOneExpr{
						pos: position{line: 23, col: 49, offset: 483},
						expr: &seqExpr{
							pos: position{line: 23, col: 50, offset: 484},
							exprs: []any{
								&zeroOrOneExpr{
									pos: position{line: 23, col: 50, offset: 484},
									expr: &ruleRefExpr{
										pos:  position{line: 23, col: 50, offset: 484},
										name: "Spacing",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 23, col: 59, offset: 493},
									name: "Currency",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Currency",
			pos:  position{line: 25, col: 1, offset: 505},
			expr: &choiceExpr{
				pos: position{line: 25, col: 13, offset: 517},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 25, col: 13, offset: 517},
						val:        "$",
						ignoreCase: false,
						want:       "\"$\"",
					},
					&litMatcher{
						pos:        position{line: 25, col: 19, offset: 523},
						val:        "€",
						ignoreCase: false,
						want:       "\"€\"",
					},
					&litMatcher{
						pos:        position{line: 25, col: 25, offset: 531},
						val:        "£",
						ignoreCase: false,
						want:       "\"£\"",
					},
					&litMatcher{
						pos:        position{line: 25, col: 31, offset: 538},
						val:        "¥",
						ignoreCase: false,
						want:       "\"¥\"",
					},
					&litMatcher{
						pos:        position{line: 25, col: 37, offset: 545},
						val:        "₹",
						ignoreCase: false,
						want:       "\"₹\"",
					},
					&litMatcher{
						pos:        position{line: 25, col: 43, offset: 553},
						val:        "₽",
						ignoreCase: false,
						want:       "\"₽\"",
					},
					&litMatcher{
						pos:        position{line: 25, col: 49, offset: 561},
						val:        "฿",
						ignoreCase: false,
						want:       "\"฿\"",
					},
					&litMatcher{
						pos:        position{line: 25, col: 55, offset: 569},
						val:        "₩",
						ignoreCase: false,
						want:       "\"₩\"",
					},
					&litMatcher{
						pos:        position{line: 25, col: 61, offset: 577},
						val:        "₫",
						ignoreCase: false,
						want:       "\"₫\"",
					},
					&litMatcher{
						pos:        position{line: 25, col: 67, offset: 585},
						val:        "₪",
						ignoreCase: false,
						want:       "\"₪\"",
					},
					&litMatcher{
						pos:        position{line: 26, col: 13, offset: 605},
						val:        "USD",
						ignoreCase: false,
						want:       "\"USD\"",
					},
					&litMatcher{
						pos:        position{line: 26, col: 21, offset: 613},
						val:        "EUR",
						ignoreCase: false,
						want:       "\"EUR\"",
					},
					&litMatcher{
						pos:        position{line: 26, col: 29, offset: 621},
						val:        "GBP",
						ignoreCase: false,
						want:       "\"GBP\"",
					},
					&litMatcher{
						pos:        position{line: 26, col: 37, offset: 629},
						val:        "JPY",
						ignoreCase: false,
						want:       "\"JPY\"",
					},
					&litMatcher{
						pos:        position{line: 26, col: 45, offset: 637},
						val:        "AUD",
						ignoreCase: false,
						want:       "\"AUD\"",
					},
					&litMatcher{
						pos:        position{line: 26, col: 53, offset: 645},
						val:        "CAD",
						ignoreCase: false,
						want:       "\"CAD\"",
					},
					&litMatcher{
						pos:        position{line: 26, col: 61, offset: 653},
						val:        "CHF",
						ignoreCase: false,
						want:       "\"CHF\"",
					},
					&litMatcher{
						pos:        position{line: 26, col: 69, offset: 661},
						val:        "CNY",
						ignoreCase: false,
						want:       "\"CNY\"",
					},
					&litMatcher{
						pos:        position{line: 27, col: 13, offset: 682},
						val:        "SEK",
						ignoreCase: false,
						want:       "\"SEK\"",
					},
					&litMatcher{
						pos:        position{line: 27, col: 21, offset: 690},
						val:        "NZD",
						ignoreCase: false,
						want:       "\"NZD\"",
					},
					&litMatcher{
						pos:        position{line: 27, col: 29, offset: 698},
						val:        "INR",
						ignoreCase: false,
						want:       "\"INR\"",
					},
					&litMatcher{
						pos:        position{line: 27, col: 37, offset: 706},
						val:        "BRL",
						ignoreCase: false,
						want:       "\"BRL\"",
					},
					&litMatcher{
						pos:        position{line: 27, col: 45, offset: 714},
						val:        "RUB",
						ignoreCase: false,
						want:       "\"RUB\"",
					},
					&litMatcher{
						pos:        position{line: 27, col: 53, offset: 722},
						val:        "ZAR",
						ignoreCase: false,
						want:       "\"ZAR\"",
					},
					&litMatcher{
						pos:        position{line: 27, col: 61, offset: 730},
						val:        "MXN",
						ignoreCase: false,
						want:       "\"MXN\"",
					},
					&litMatcher{
						pos:        position{line: 27, col: 69, offset: 738},
						val:        "SGD",
						ignoreCase: false,
						want:       "\"SGD\"",
					},
					&litMatcher{
						pos:        position{line: 28, col: 13, offset: 759},
						val:        "HKD",
						ignoreCase: false,
						want:       "\"HKD\"",
					},
					&litMatcher{
						pos:        position{line: 28, col: 21, offset: 767},
						val:        "NOK",
						ignoreCase: false,
						want:       "\"NOK\"",
					},
					&litMatcher{
						pos:        position{line: 28, col: 29, offset: 775},
						val:        "KRW",
						ignoreCase: false,
						want:       "\"KRW\"",
					},
					&litMatcher{
						pos:        position{line: 28, col: 37, offset: 783},
						val:        "TRY",
						ignoreCase: false,
						want:       "\"TRY\"",
					},
					&litMatcher{
						pos:        position{line: 28, col: 45, offset: 791},
						val:        "AED",
						ignoreCase: false,
						want:       "\"AED\"",
					},
					&litMatcher{
						pos:        position{line: 28, col: 53, offset: 799},
						val:        "SAR",
						ignoreCase: false,
						want:       "\"SAR\"",
					},
					&litMatcher{
						pos:        position{line: 28, col: 61, offset: 807},
						val:        "IRR",
						ignoreCase: false,
						want:       "\"IRR\"",
					},
					&litMatcher{
						pos:        position{line: 28, col: 69, offset: 815},
						val:        "IDR",
						ignoreCase: false,
						want:       "\"IDR\"",
					},
					&litMatcher{
						pos:        position{line: 29, col: 13, offset: 836},
						val:        "MYR",
						ignoreCase: false,
						want:       "\"MYR\"",
					},
					&litMatcher{
						pos:        position{line: 29, col: 21, offset: 844},
						val:        "PHP",
						ignoreCase: false,
						want:       "\"PHP\"",
					},
					&litMatcher{
						pos:        position{line: 29, col: 29, offset: 852},
						val:        "VND",
						ignoreCase: false,
						want:       "\"VND\"",
					},
					&litMatcher{
						pos:        position{line: 29, col: 37, offset: 860},
						val:        "ILS",
						ignoreCase: false,
						want:       "\"ILS\"",
					},
					&litMatcher{
						pos:        position{line: 29, col: 45, offset: 868},
						val:        "PLN",
						ignoreCase: false,
						want:       "\"PLN\"",
					},
					&litMatcher{
						pos:        position{line: 29, col: 53, offset: 876},
						val:        "CZK",
						ignoreCase: false,
						want:       "\"CZK\"",
					},
					&litMatcher{
						pos:        position{line: 29, col: 61, offset: 884},
						val:        "HUF",
						ignoreCase: false,
						want:       "\"HUF\"",
					},
					&litMatcher{
						pos:        position{line: 29, col: 69, offset: 892},
						val:        "RON",
						ignoreCase: false,
						want:       "\"RON\"",
					},
					&litMatcher{
						pos:        position{line: 29, col: 77, offset: 900},
						val:        "THB",
						ignoreCase: false,
						want:       "\"THB\"",
					},
				},
			},
		},
		{
			name: "Amount",
			pos:  position{line: 31, col: 1, offset: 907},
			expr: &seqExpr{
				pos: position{line: 31, col: 11, offset: 917},
				exprs: []any{
					&oneOrMoreExpr{
						pos: position{line: 31, col: 11, offset: 917},
						expr: &charClassMatcher{
							pos:        position{line: 31, col: 11, offset: 917},
							val:        "[0-9,]",
							chars:      []rune{','},
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&zeroOrOneExpr{
						pos: position{line: 31, col: 19, offset: 925},
						expr: &seqExpr{
							pos: position{line: 31, col: 21, offset: 927},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 31, col: 21, offset: 927},
									val:        ".",
									ignoreCase: false,
									want:       "\".\"",
								},
								&oneOrMoreExpr{
									pos: position{line: 31, col: 25, offset: 931},
									expr: &charClassMatcher{
										pos:        position{line: 31, col: 25, offset: 931},
										val:        "[0-9]",
										ranges:     []rune{'0', '9'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Frequency",
			pos:  position{line: 32, col: 1, offset: 941},
			expr: &seqExpr{
				pos: position{line: 32, col: 14, offset: 954},
				exprs: []any{
					&zeroOrOneExpr{
						pos: position{line: 32, col: 14, offset: 954},
						expr: &choiceExpr{
							pos: position{line: 32, col: 15, offset: 955},
							alternatives: []any{
								&litMatcher{
									pos:        position{line: 32, col: 15, offset: 955},
									val:        "per",
									ignoreCase: true,
									want:       "\"per\"i",
								},
								&litMatcher{
									pos:        position{line: 32, col: 24, offset: 964},
									val:        "/",
									ignoreCase: false,
									want:       "\"/\"",
								},
							},
						},
					},
					&zeroOrOneExpr{
						pos: position{line: 32, col: 30, offset: 970},
						expr: &ruleRefExpr{
							pos:  position{line: 32, col: 30, offset: 970},
							name: "Spacing",
						},
					},
					&choiceExpr{
						pos: position{line: 32, col: 40, offset: 980},
						alternatives: []any{
							&litMatcher{
								pos:        position{line: 32, col: 40, offset: 980},
								val:        "year",
								ignoreCase: true,
								want:       "\"year\"i",
							},
							&litMatcher{
								pos:        position{line: 32, col: 50, offset: 990},
								val:        "yr",
								ignoreCase: true,
								want:       "\"yr\"i",
							},
							&litMatcher{
								pos:        position{line: 32, col: 58, offset: 998},
								val:        "annually",
								ignoreCase: true,
								want:       "\"annually\"i",
							},
							&litMatcher{
								pos:        position{line: 32, col: 72, offset: 1012},
								val:        "pa",
								ignoreCase: true,
								want:       "\"pa\"i",
							},
							&litMatcher{
								pos:        position{line: 32, col: 80, offset: 1020},
								val:        "p.a.",
								ignoreCase: true,
								want:       "\"p.a.\"i",
							},
							&litMatcher{
								pos:        position{line: 32, col: 90, offset: 1030},
								val:        "month",
								ignoreCase: true,
								want:       "\"month\"i",
							},
							&litMatcher{
								pos:        position{line: 32, col: 101, offset: 1041},
								val:        "mo",
								ignoreCase: true,
								want:       "\"mo\"i",
							},
							&litMatcher{
								pos:        position{line: 32, col: 109, offset: 1049},
								val:        "hour",
								ignoreCase: true,
								want:       "\"hour\"i",
							},
							&litMatcher{
								pos:        position{line: 32, col: 119, offset: 1059},
								val:        "hr",
								ignoreCase: true,
								want:       "\"hr\"i",
							},
							&litMatcher{
								pos:        position{line: 32, col: 127, offset: 1067},
								val:        "day",
								ignoreCase: true,
								want:       "\"day\"i",
							},
						},
					},
				},
			},
		},
		{
			name: "Spacing",
			pos:  position{line: 33, col: 1, offset: 1075},
			expr: &oneOrMoreExpr{
				pos: position{line: 33, col: 12, offset: 1086},
				expr: &charClassMatcher{
					pos:        position{line: 33, col: 12, offset: 1086},
					val:        "[ \\t\\n\\r]",
					chars:      []rune{' ', '\t', '\n', '\r'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "Location",
			pos:  position{line: 35, col: 1, offset: 1098},
			expr: &actionExpr{
				pos: position{line: 35, col: 13, offset: 1110},
				run: (*parser).callonLocation1,
				expr: &choiceExpr{
					pos: position{line: 35, col: 14, offset: 1111},
					alternatives: []any{
						&ruleRefExpr{
							pos:  position{line: 35, col: 14, offset: 1111},
							name: "Remote",
						},
						&ruleRefExpr{
							pos:  position{line: 35, col: 23, offset: 1120},
							name: "OnSite",
						},
						&ruleRefExpr{
							pos:  position{line: 35, col: 32, offset: 1129},
							name: "Hybrid",
						},
						&ruleRefExpr{
							pos:  position{line: 35, col: 41, offset: 1138},
							name: "CityState",
						},
					},
				},
			},
		},
		{
			name: "Remote",
			pos:  position{line: 39, col: 1, offset: 1185},
			expr: &litMatcher{
				pos:        position{line: 39, col: 11, offset: 1195},
				val:        "remote",
				ignoreCase: true,
				want:       "\"remote\"i",
			},
		},
		{
			name: "OnSite",
			pos:  position{line: 40, col: 1, offset: 1205},
			expr: &choiceExpr{
				pos: position{line: 40, col: 11, offset: 1215},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 40, col: 11, offset: 1215},
						val:        "on-site",
						ignoreCase: true,
						want:       "\"on-site\"i",
					},
					&litMatcher{
						pos:        position{line: 40, col: 24, offset: 1228},
						val:        "onsite",
						ignoreCase: true,
						want:       "\"onsite\"i",
					},
				},
			},
		},
		{
			name: "Hybrid",
			pos:  position{line: 41, col: 1, offset: 1238},
			expr: &litMatcher{
				pos:        position{line: 41, col: 11, offset: 1248},
				val:        "hybrid",
				ignoreCase: true,
				want:       "\"hybrid\"i",
			},
		},
		{
			name: "CityState",
			pos:  position{line: 42, col: 1, offset: 1258},
			expr: &seqExpr{
				pos: position{line: 42, col: 14, offset: 1271},
				exprs: []any{
					&charClassMatcher{
						pos:        position{line: 42, col: 14, offset: 1271},
						val:        "[A-Z]",
						ranges:     []rune{'A', 'Z'},
						ignoreCase: false,
						inverted:   false,
					},
					&oneOrMoreExpr{
						pos: position{line: 42, col: 19, offset: 1276},
						expr: &charClassMatcher{
							pos:        position{line: 42, col: 19, offset: 1276},
							val:        "[a-z]",
							ranges:     []rune{'a', 'z'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&zeroOrMoreExpr{
						pos: position{line: 42, col: 26, offset: 1283},
						expr: &seqExpr{
							pos: position{line: 42, col: 27, offset: 1284},
							exprs: []any{
								&ruleRefExpr{
									pos:  position{line: 42, col: 27, offset: 1284},
									name: "Spacing",
								},
								&charClassMatcher{
									pos:        position{line: 42, col: 35, offset: 1292},
									val:        "[A-Z]",
									ranges:     []rune{'A', 'Z'},
									ignoreCase: false,
									inverted:   false,
								},
								&oneOrMoreExpr{
									pos: position{line: 42, col: 40, offset: 1297},
									expr: &charClassMatcher{
										pos:        position{line: 42, col: 40, offset: 1297},
										val:        "[a-z]",
										ranges:     []rune{'a', 'z'},
										ignoreCase: false,
										inverted:   false,
									},
								},
							},
						},
					},
					&litMatcher{
						pos:        position{line: 42, col: 49, offset: 1306},
						val:        ",",
						ignoreCase: false,
						want:       "\",\"",
					},
					&zeroOrOneExpr{
						pos: position{line: 42, col: 53, offset: 1310},
						expr: &ruleRefExpr{
							pos:  position{line: 42, col: 53, offset: 1310},
							name: "Spacing",
						},
					},
					&charClassMatcher{
						pos:        position{line: 42, col: 62, offset: 1319},
						val:        "[A-Z]",
						ranges:     []rune{'A', 'Z'},
						ignoreCase: false,
						inverted:   false,
					},
					&oneOrMoreExpr{
						pos: position{line: 42, col: 67, offset: 1324},
						expr: &charClassMatcher{
							pos:        position{line: 42, col: 67, offset: 1324},
							val:        "[A-Z]",
							ranges:     []rune{'A', 'Z'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "URL",
			pos:  position{line: 44, col: 1, offset: 1332},
			expr: &actionExpr{
				pos: position{line: 44, col: 8, offset: 1339},
				run: (*parser).callonURL1,
				expr: &seqExpr{
					pos: position{line: 44, col: 8, offset: 1339},
					exprs: []any{
						&ruleRefExpr{
							pos:  position{line: 44, col: 8, offset: 1339},
							name: "Scheme",
						},
						&litMatcher{
							pos:        position{line: 44, col: 15, offset: 1346},
							val:        "://",
							ignoreCase: false,
							want:       "\"://\"",
						},
						&ruleRefExpr{
							pos:  position{line: 44, col: 21, offset: 1352},
							name: "Host",
						},
						&zeroOrOneExpr{
							pos: position{line: 44, col: 26, offset: 1357},
							expr: &ruleRefExpr{
								pos:  position{line: 44, col: 26, offset: 1357},
								name: "Path",
							},
						},
					},
				},
			},
		},
		{
			name: "Scheme",
			pos:  position{line: 48, col: 1, offset: 1399},
			expr: &seqExpr{
				pos: position{line: 48, col: 11, offset: 1409},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 48, col: 11, offset: 1409},
						val:        "http",
						ignoreCase: false,
						want:       "\"http\"",
					},
					&zeroOrOneExpr{
						pos: position{line: 48, col: 18, offset: 1416},
						expr: &litMatcher{
							pos:        position{line: 48, col: 18, offset: 1416},
							val:        "s",
							ignoreCase: false,
							want:       "\"s\"",
						},
					},
				},
			},
		},
		{
			name: "Host",
			pos:  position{line: 49, col: 1, offset: 1421},
			expr: &seqExpr{
				pos: position{line: 49, col: 9, offset: 1429},
				exprs: []any{
					&oneOrMoreExpr{
						pos: position{line: 49, col: 9, offset: 1429},
						expr: &charClassMatcher{
							pos:        position{line: 49, col: 9, offset: 1429},
							val:        "[^ \\t\\n\\r<>/\":]",
							chars:      []rune{' ', '\t', '\n', '\r', '<', '>', '/', '"', ':'},
							ignoreCase: false,
							inverted:   true,
						},
					},
					&zeroOrOneExpr{
						pos: position{line: 49, col: 26, offset: 1446},
						expr: &seqExpr{
							pos: position{line: 49, col: 27, offset: 1447},
							exprs: []any{
								&litMatcher{
									pos:        position{line: 49, col: 27, offset: 1447},
									val:        ":",
									ignoreCase: false,
									want:       "\":\"",
								},
								&ruleRefExpr{
									pos:  position{line: 49, col: 31, offset: 1451},
									name: "Port",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Port",
			pos:  position{line: 50, col: 1, offset: 1458},
			expr: &oneOrMoreExpr{
				pos: position{line: 50, col: 9, offset: 1466},
				expr: &charClassMatcher{
					pos:        position{line: 50, col: 9, offset: 1466},
					val:        "[0-9]",
					ranges:     []rune{'0', '9'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "Path",
			pos:  position{line: 51, col: 1, offset: 1473},
			expr: &seqExpr{
				pos: position{line: 51, col: 9, offset: 1481},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 51, col: 9, offset: 1481},
						val:        "/",
						ignoreCase: false,
						want:       "\"/\"",
					},
					&zeroOrMoreExpr{
						pos: position{line: 51, col: 13, offset: 1485},
						expr: &charClassMatcher{
							pos:        position{line: 51, col: 13, offset: 1485},
							val:        "[^ \\t\\n\\r<>\"]",
							chars:      []rune{' ', '\t', '\n', '\r', '<', '>', '"'},
							ignoreCase: false,
							inverted:   true,
						},
					},
				},
			},
		},
		{
			name: "Trap",
			pos:  position{line: 53, col: 1, offset: 1501},
			expr: &actionExpr{
				pos: position{line: 53, col: 9, offset: 1509},
				run: (*parser).callonTrap1,
				expr: &choiceExpr{
					pos: position{line: 53, col: 10, offset: 1510},
					alternatives: []any{
						&ruleRefExpr{
							pos:  position{line: 53, col: 10, offset: 1510},
							name: "Jailbreak",
						},
						&ruleRefExpr{
							pos:  position{line: 53, col: 22, offset: 1522},
							name: "Instruction",
						},
						&ruleRefExpr{
							pos:  position{line: 53, col: 36, offset: 1536},
							name: "Codeword",
						},
						&ruleRefExpr{
							pos:  position{line: 53, col: 47, offset: 1547},
							name: "Math",
						},
					},
				},
			},
		},
		{
			name: "Jailbreak",
			pos:  position{line: 57, col: 1, offset: 1589},
			expr: &choiceExpr{
				pos: position{line: 57, col: 14, offset: 1602},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 57, col: 14, offset: 1602},
						val:        "ignore all previous instructions",
						ignoreCase: true,
						want:       "\"ignore all previous instructions\"i",
					},
					&litMatcher{
						pos:        position{line: 57, col: 52, offset: 1640},
						val:        "ignore previous instructions",
						ignoreCase: true,
						want:       "\"ignore previous instructions\"i",
					},
					&litMatcher{
						pos:        position{line: 58, col: 14, offset: 1688},
						val:        "disregard all previous",
						ignoreCase: true,
						want:       "\"disregard all previous\"i",
					},
					&litMatcher{
						pos:        position{line: 58, col: 42, offset: 1716},
						val:        "forget your previous",
						ignoreCase: true,
						want:       "\"forget your previous\"i",
					},
					&litMatcher{
						pos:        position{line: 58, col: 68, offset: 1742},
						val:        "bypass",
						ignoreCase: true,
						want:       "\"bypass\"i",
					},
					&litMatcher{
						pos:        position{line: 59, col: 14, offset: 1768},
						val:        "system prompt",
						ignoreCase: true,
						want:       "\"system prompt\"i",
					},
					&litMatcher{
						pos:        position{line: 59, col: 33, offset: 1787},
						val:        "you are now",
						ignoreCase: true,
						want:       "\"you are now\"i",
					},
					&litMatcher{
						pos:        position{line: 59, col: 50, offset: 1804},
						val:        "act as",
						ignoreCase: true,
						want:       "\"act as\"i",
					},
				},
			},
		},
		{
			name: "Instruction",
			pos:  position{line: 61, col: 1, offset: 1815},
			expr: &choiceExpr{
				pos: position{line: 61, col: 16, offset: 1830},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 61, col: 16, offset: 1830},
						val:        "write a cover letter about",
						ignoreCase: true,
						want:       "\"write a cover letter about\"i",
					},
					&litMatcher{
						pos:        position{line: 61, col: 48, offset: 1862},
						val:        "start your cover letter with",
						ignoreCase: true,
						want:       "\"start your cover letter with\"i",
					},
					&litMatcher{
						pos:        position{line: 62, col: 16, offset: 1912},
						val:        "include the word",
						ignoreCase: true,
						want:       "\"include the word\"i",
					},
					&litMatcher{
						pos:        position{line: 62, col: 38, offset: 1934},
						val:        "mention this word",
						ignoreCase: true,
						want:       "\"mention this word\"i",
					},
					&litMatcher{
						pos:        position{line: 62, col: 61, offset: 1957},
						val:        "mention the word",
						ignoreCase: true,
						want:       "\"mention the word\"i",
					},
					&litMatcher{
						pos:        position{line: 63, col: 16, offset: 1994},
						val:        "no ai",
						ignoreCase: true,
						want:       "\"no ai\"i",
					},
					&litMatcher{
						pos:        position{line: 63, col: 27, offset: 2005},
						val:        "no llm",
						ignoreCase: true,
						want:       "\"no llm\"i",
					},
					&litMatcher{
						pos:        position{line: 63, col: 39, offset: 2017},
						val:        "no chatgpt",
						ignoreCase: true,
						want:       "\"no chatgpt\"i",
					},
					&litMatcher{
						pos:        position{line: 63, col: 55, offset: 2033},
						val:        "human only",
						ignoreCase: true,
						want:       "\"human only\"i",
					},
					&litMatcher{
						pos:        position{line: 63, col: 71, offset: 2049},
						val:        "not a bot",
						ignoreCase: true,
						want:       "\"not a bot\"i",
					},
					&litMatcher{
						pos:        position{line: 64, col: 16, offset: 2079},
						val:        "word count",
						ignoreCase: true,
						want:       "\"word count\"i",
					},
					&litMatcher{
						pos:        position{line: 64, col: 32, offset: 2095},
						val:        "how many times does the letter",
						ignoreCase: true,
						want:       "\"how many times does the letter\"i",
					},
					&litMatcher{
						pos:        position{line: 64, col: 68, offset: 2131},
						val:        "recipe for",
						ignoreCase: true,
						want:       "\"recipe for\"i",
					},
					&litMatcher{
						pos:        position{line: 65, col: 16, offset: 2162},
						val:        "summarize this as",
						ignoreCase: true,
						want:       "\"summarize this as\"i",
					},
					&litMatcher{
						pos:        position{line: 65, col: 39, offset: 2185},
						val:        "translate to",
						ignoreCase: true,
						want:       "\"translate to\"i",
					},
				},
			},
		},
		{
			name: "Codeword",
			pos:  position{line: 67, col: 1, offset: 2202},
			expr: &choiceExpr{
				pos: position{line: 67, col: 13, offset: 2214},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 67, col: 13, offset: 2214},
						val:        "brown m&m",
						ignoreCase: true,
						want:       "\"brown m&m\"i",
					},
					&litMatcher{
						pos:        position{line: 67, col: 28, offset: 2229},
						val:        "blue m&m",
						ignoreCase: true,
						want:       "\"blue m&m\"i",
					},
					&litMatcher{
						pos:        position{line: 67, col: 42, offset: 2243},
						val:        "banana",
						ignoreCase: true,
						want:       "\"banana\"i",
					},
					&litMatcher{
						pos:        position{line: 67, col: 54, offset: 2255},
						val:        "pineapple",
						ignoreCase: true,
						want:       "\"pineapple\"i",
					},
					&litMatcher{
						pos:        position{line: 67, col: 69, offset: 2270},
						val:        "purple elephant",
						ignoreCase: true,
						want:       "\"purple elephant\"i",
					},
					&litMatcher{
						pos:        position{line: 68, col: 13, offset: 2303},
						val:        "codeword",
						ignoreCase: true,
						want:       "\"codeword\"i",
					},
					&litMatcher{
						pos:        position{line: 68, col: 27, offset: 2317},
						val:        "secret word",
						ignoreCase: true,
						want:       "\"secret word\"i",
					},
				},
			},
		},
		{
			name: "Math",
			pos:  position{line: 70, col: 1, offset: 2333},
			expr: &choiceExpr{
				pos: position{line: 70, col: 9, offset: 2341},
				alternatives: []any{
					&litMatcher{
						pos:        position{line: 70, col: 9, offset: 2341},
						val:        "solve this math",
						ignoreCase: true,
						want:       "\"solve this math\"i",
					},
					&litMatcher{
						pos:        position{line: 70, col: 30, offset: 2362},
						val:        "add the result of",
						ignoreCase: true,
						want:       "\"add the result of\"i",
					},
					&litMatcher{
						pos:        position{line: 70, col: 53, offset: 2385},
						val:        "calculate",
						ignoreCase: true,
						want:       "\"calculate\"i",
					},
					&litMatcher{
						pos:        position{line: 70, col: 68, offset: 2400},
						val:        "add the sha256",
						ignoreCase: true,
						want:       "\"add the sha256\"i",
					},
				},
			},
		},
	},
}

func (c *current) onEmail1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonEmail1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onEmail1()
}

func (c *current) onSalary1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonSalary1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSalary1()
}

func (c *current) onLocation1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonLocation1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLocation1()
}

func (c *current) onURL1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonURL1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onURL1()
}

func (c *current) onTrap1() (any, error) {
	return string(c.text), nil
}

func (p *parser) callonTrap1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTrap1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
