package compose

import (
	"fmt"
	"strings"

	tea "github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
	"sprayer/src/ui/tui/theme"
)

// envField names for the envelope.
var envLabels = []string{"From", "To", "Subject", "Attach"}

// Model holds compose screen state.
type Model struct {
	From       string
	To         string
	Subject    string
	Attach     string
	Body       string
	FocusField int  // 0-3 for envelope fields
	EditBody   bool // true when editing body
	Generated  bool
	Company    string
	Score      int
	Width      int
	Height     int
}

// New creates a compose model from an email.
func New(from, to, subject, attach, body, company string, score, w, h int) Model {
	return Model{
		From:       from,
		To:         to,
		Subject:    subject,
		Attach:     attach,
		Body:       body,
		FocusField: 2, // subject focused by default
		Generated:  true,
		Company:    company,
		Score:      score,
		Width:      w,
		Height:     h,
	}
}

// BackMsg signals going back to emails.
type BackMsg struct{}

// SendMsg signals sending the email.
type SendMsg struct{}

// RegenerateMsg signals regenerating the body.
type RegenerateMsg struct{}

// Update handles compose key events.
func (m Model) Update(msg tea.Msg) (Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tea.KeyMsg:
		if m.EditBody {
			switch msg.String() {
			case "esc":
				m.EditBody = false
			case "backspace":
				if len(m.Body) > 0 {
					m.Body = m.Body[:len(m.Body)-1]
				}
			case "enter":
				m.Body += "\n"
			default:
				if len(msg.String()) == 1 || msg.String() == " " {
					m.Body += msg.String()
				}
			}
			return m, nil
		}

		switch msg.String() {
		case "tab":
			m.FocusField = (m.FocusField + 1) % 4
		case "shift+tab":
			m.FocusField = (m.FocusField - 1 + 4) % 4
		case "e":
			m.EditBody = true
		case "ctrl+s":
			return m, func() tea.Msg { return SendMsg{} }
		case "ctrl+r":
			return m, func() tea.Msg { return RegenerateMsg{} }
		case "esc":
			return m, func() tea.Msg { return BackMsg{} }
		case "backspace":
			field := m.getField()
			if len(*field) > 0 {
				*field = (*field)[:len(*field)-1]
			}
		default:
			if len(msg.String()) == 1 || msg.String() == " " {
				field := m.getField()
				*field += msg.String()
			}
		}
	}
	return m, nil
}

func (m *Model) getField() *string {
	switch m.FocusField {
	case 0:
		return &m.From
	case 1:
		return &m.To
	case 2:
		return &m.Subject
	case 3:
		return &m.Attach
	}
	return &m.Subject
}

// WordCount returns the word count of the body.
func (m Model) WordCount() int {
	words := strings.Fields(m.Body)
	return len(words)
}

// View renders the compose screen.
func (m Model) View() string {
	contentH := m.Height - 2
	if contentH < 1 {
		contentH = 1
	}

	var sections []string

	// Envelope fields
	fields := []string{m.From, m.To, m.Subject, m.Attach}
	for i, label := range envLabels {
		active := i == m.FocusField && !m.EditBody
		val := fields[i]

		var lblStyle, valStyle lipgloss.Style
		var rowBg lipgloss.Color

		if active {
			lblStyle = theme.PopLabelActiveStyle
			valStyle = lipgloss.NewStyle().Foreground(theme.Bright)
			rowBg = lipgloss.Color("#13102a")
		} else {
			lblStyle = theme.PopLabelStyle
			if i == 1 { // "To" field gets cyan
				valStyle = lipgloss.NewStyle().Foreground(theme.Cyan)
			} else if i == 3 { // "Attach" gets muted
				valStyle = lipgloss.NewStyle().Foreground(theme.Muted)
			} else {
				valStyle = lipgloss.NewStyle().Foreground(theme.Text)
			}
			rowBg = theme.Background
		}

		labelW := 10
		lbl := lblStyle.Background(rowBg).Width(labelW).Align(lipgloss.Right).Render(label)
		sep := lipgloss.NewStyle().Background(rowBg).Render("  ")
		v := valStyle.Background(rowBg).Render(val)
		cursor := ""
		if active {
			cursor = theme.CursorStyle.Render("|")
		}

		row := lipgloss.NewStyle().
			Background(rowBg).
			Width(m.Width).
			PaddingLeft(1).
			Render(lbl + sep + v + cursor)

		sections = append(sections, row)
	}

	// Separator
	sections = append(sections,
		lipgloss.NewStyle().Background(theme.Background).
			Foreground(theme.BorderColor).
			Width(m.Width).
			Render(strings.Repeat("-", m.Width)))

	// Generation hint
	if m.Generated {
		pulse := theme.PopGenHintStyle.Render("*")
		hint := theme.PopGenHintStyle.Render(" generated by mods  ·  ctrl+r to regenerate")
		hintRow := lipgloss.NewStyle().
			Background(theme.Background).
			Width(m.Width).
			PaddingLeft(2).
			Render(pulse + hint)
		sections = append(sections, hintRow)

		sections = append(sections,
			lipgloss.NewStyle().Background(theme.Background).
				Foreground(theme.BorderColor).
				Width(m.Width).
				Render(strings.Repeat("-", m.Width)))
	}

	// Body
	bodyH := contentH - len(sections)
	if bodyH < 3 {
		bodyH = 3
	}

	bodyContent := m.Body
	if m.EditBody {
		bodyContent += theme.CursorStyle.Render("|")
	}

	body := theme.PopBodyStyle.
		Width(m.Width - 6).
		Height(bodyH).
		Padding(1, 2).
		Render(bodyContent)

	sections = append(sections, body)

	return lipgloss.JoinVertical(lipgloss.Left, sections...)
}

// TopBarRight returns "Company · Score: N".
func (m Model) TopBarRight() string {
	return fmt.Sprintf("%s  ·  Score: %d", m.Company, m.Score)
}
